//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class AsignacionesMaquinariaPage
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Label lblTotalAsignaciones;
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;
        protected global::System.Web.UI.WebControls.DropDownList ddlOperador;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvOperador;
        protected global::System.Web.UI.WebControls.DropDownList ddlEquipo;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEquipo;
        protected global::System.Web.UI.WebControls.DropDownList ddlObra;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvObra;
        protected global::System.Web.UI.WebControls.TextBox txtFechaAsignacion;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFecha;
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;
        protected global::System.Web.UI.WebControls.Button btnAsignar;
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroEstado;
        protected global::System.Web.UI.WebControls.GridView gvAsignaciones;
    }
}
