//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class DashboardGrifo
    {
        protected global::System.Web.UI.WebControls.HiddenField hfTabActiva;
        protected global::System.Web.UI.WebControls.Label lblAbastecimientosHoy;
        protected global::System.Web.UI.WebControls.Label lblGalonesHoy;
        protected global::System.Web.UI.WebControls.Label lblTotalViajesActivos;
        protected global::System.Web.UI.WebControls.Label lblTotalAbastecimientos;
        protected global::System.Web.UI.WebControls.TextBox txtBuscarConductor;
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;
        protected global::System.Web.UI.WebControls.Button btnFiltrar;
        protected global::System.Web.UI.WebControls.Button btnRefrescar;
        protected global::System.Web.UI.WebControls.Panel pnlViajes;
        protected global::System.Web.UI.WebControls.Repeater rptViajesActivos;
        protected global::System.Web.UI.WebControls.Panel pnlSinViajes;
        protected global::System.Web.UI.WebControls.TextBox txtFechaDesde;
        protected global::System.Web.UI.WebControls.TextBox txtFechaHasta;
        protected global::System.Web.UI.WebControls.TextBox txtBuscarAbastecimiento;
        protected global::System.Web.UI.WebControls.Button btnFiltrarHistorial;
        protected global::System.Web.UI.WebControls.Button btnLimpiarHistorial;
        protected global::System.Web.UI.WebControls.Panel pnlAbastecimientos;
        protected global::System.Web.UI.WebControls.Repeater rptAbastecimientos;
        protected global::System.Web.UI.WebControls.Panel pnlSinAbastecimientos;
        protected global::System.Web.UI.WebControls.Label lblTotalRetornos;
        protected global::System.Web.UI.WebControls.Label lblTotalGalonesEcuador;
        protected global::System.Web.UI.WebControls.Label lblTotalUsdEcuador;
        protected global::System.Web.UI.WebControls.Panel pnlRetornos;
        protected global::System.Web.UI.WebControls.Repeater rptRetornos;
        protected global::System.Web.UI.WebControls.Panel pnlSinRetornos;
    }
}
