//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class DashboardOperador
    {
        protected global::System.Web.UI.WebControls.HiddenField hfIdOperador;
        protected global::System.Web.UI.WebControls.HiddenField hfIdAsignacion;
        protected global::System.Web.UI.WebControls.Label lblNombreOperador;
        protected global::System.Web.UI.WebControls.Label lblDNIOperador;
        protected global::System.Web.UI.WebControls.Label lblFechaHoy;
        protected global::System.Web.UI.WebControls.Panel pnlAsignacion;
        protected global::System.Web.UI.WebControls.Label lblPlacaEquipo;
        protected global::System.Web.UI.WebControls.Label lblTipoEquipo;
        protected global::System.Web.UI.WebControls.Label lblClienteObra;
        protected global::System.Web.UI.WebControls.Label lblNombreObra;
        protected global::System.Web.UI.WebControls.Panel pnlSinAsignacion;
        protected global::System.Web.UI.WebControls.Panel pnlContenido;
        protected global::System.Web.UI.WebControls.Label lblCantidadPartes;
        protected global::System.Web.UI.WebControls.TextBox txtFechaParte;
        protected global::System.Web.UI.WebControls.TextBox txtNumeroParte;
        protected global::System.Web.UI.WebControls.TextBox txtOdometroComienzo;
        protected global::System.Web.UI.WebControls.TextBox txtOdometroTermino;
        protected global::System.Web.UI.WebControls.TextBox txtOdometroKmHoras;
        protected global::System.Web.UI.WebControls.TextBox txtHorometroComienzo;
        protected global::System.Web.UI.WebControls.TextBox txtHorometroTermino;
        protected global::System.Web.UI.WebControls.TextBox txtHorometroHoras;
        protected global::System.Web.UI.WebControls.TextBox txtConsumoPetroleo;
        protected global::System.Web.UI.WebControls.TextBox txtConsumoGasolina;
        protected global::System.Web.UI.WebControls.TextBox txtConsumoAceite;
        protected global::System.Web.UI.WebControls.TextBox txtConsumoGrasa;
        protected global::System.Web.UI.WebControls.TextBox txtCarretera;
        protected global::System.Web.UI.WebControls.TextBox txtSector;
        protected global::System.Web.UI.WebControls.TextBox txtSectorKm;
        protected global::System.Web.UI.WebControls.TextBox txtAlKm;
        protected global::System.Web.UI.WebControls.TextBox txtLabor;
        protected global::System.Web.UI.WebControls.TextBox txtCodigo;
        protected global::System.Web.UI.WebControls.TextBox txtCantidadViajes;
        protected global::System.Web.UI.WebControls.TextBox txtReclamo;
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Button btnLimpiar;
        protected global::System.Web.UI.WebControls.Button btnGuardarParte;
        protected global::System.Web.UI.WebControls.Panel pnlHistorial;
        protected global::System.Web.UI.WebControls.Label lblTotalPartes;
        protected global::System.Web.UI.WebControls.Label lblTotalHoras;
        protected global::System.Web.UI.WebControls.Repeater rptHistorial;
        protected global::System.Web.UI.WebControls.Panel pnlHistorialVacio;
        protected global::System.Web.UI.WebControls.Panel pnlHistorialSinAsignacion;
        protected global::System.Web.UI.WebControls.Panel pnlHistSA;
        protected global::System.Web.UI.WebControls.Label lblTotalPartesSA;
        protected global::System.Web.UI.WebControls.Label lblTotalHorasSA;
        protected global::System.Web.UI.WebControls.Repeater rptHistorialSA;
        protected global::System.Web.UI.WebControls.Panel pnlHistSAVacio;
    }
}
