//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class DetalleOrdenViaje
    {
        protected global::System.Web.UI.WebControls.Label lblNumeroOrden;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Label lblError;
        protected global::System.Web.UI.WebControls.Panel pnlContenido;

        // Información General
        protected global::System.Web.UI.WebControls.Label lblOrdenDetalle;
        protected global::System.Web.UI.WebControls.Label lblConductorDetalle;
        protected global::System.Web.UI.WebControls.Label lblTractoDetalle;
        protected global::System.Web.UI.WebControls.Label lblCarretaDetalle;
        protected global::System.Web.UI.WebControls.Label lblFechaSalidaDetalle;
        protected global::System.Web.UI.WebControls.Label lblFechaLlegadaDetalle;
        protected global::System.Web.UI.WebControls.Label lblHoraSalidaDetalle;
        protected global::System.Web.UI.WebControls.Label lblHoraLlegadaDetalle;
        protected global::System.Web.UI.WebControls.Label lblEstadoDetalle;
        protected global::System.Web.UI.WebControls.Label lblObservacionesDetalle;

        // Ingresos
        protected global::System.Web.UI.WebControls.Repeater rptIngresos;
        protected global::System.Web.UI.WebControls.Label lblTotalIngresosSoles;
        protected global::System.Web.UI.WebControls.Label lblTotalIngresosDolares;

        // Gastos
        protected global::System.Web.UI.WebControls.Repeater rptGastos;
        protected global::System.Web.UI.WebControls.Label lblTotalGastosSoles;
        protected global::System.Web.UI.WebControls.Label lblTotalGastosDolares;

        // Detalles de peajes
        protected global::System.Web.UI.WebControls.Panel pnlDetallePeajes;
        protected global::System.Web.UI.WebControls.GridView gvPeajes;

        // Detalles de reparaciones
        protected global::System.Web.UI.WebControls.Panel pnlDetalleReparaciones;
        protected global::System.Web.UI.WebControls.GridView gvReparaciones;

        // Detalles de hospedaje
        protected global::System.Web.UI.WebControls.Panel pnlDetalleHospedaje;
        protected global::System.Web.UI.WebControls.GridView gvHospedaje;

        // Detalles de combustible
        protected global::System.Web.UI.WebControls.Panel pnlDetalleCombustible;
        protected global::System.Web.UI.WebControls.GridView gvCombustible;

        // Balance final
        protected global::System.Web.UI.WebControls.Label lblBalanceSoles;
        protected global::System.Web.UI.WebControls.Label lblBalanceDolares;
    }
}
