//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto
//     y se perderán si el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class FirmarLiquidacion
    {
        /// <summary>
        /// Control form1.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control hfIdOrdenViaje.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfIdOrdenViaje;
    }
}
