//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class RegistroObras
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Label lblTotalObras;
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;
        protected global::System.Web.UI.WebControls.DropDownList ddlCliente;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCliente;
        protected global::System.Web.UI.WebControls.TextBox txtUbicacion;
        protected global::System.Web.UI.WebControls.TextBox txtFechaInicio;
        protected global::System.Web.UI.WebControls.TextBox txtFechaFin;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
        protected global::System.Web.UI.WebControls.GridView gvObras;
    }
}
