//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     El código generado está sujeto a los términos de Microsoft Public License.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class RegistrarRetornoEcuador
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litNumeroViaje;
        protected global::System.Web.UI.WebControls.Literal litConductor;
        protected global::System.Web.UI.WebControls.Literal litTracto;
        protected global::System.Web.UI.WebControls.TextBox txtFecha;
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;
        protected global::System.Web.UI.WebControls.HiddenField hfIdViaje;
        protected global::System.Web.UI.WebControls.HiddenField hfIdConductor;
        protected global::System.Web.UI.WebControls.HiddenField hfIdTracto;
        protected global::System.Web.UI.WebControls.HiddenField hfTicketsJson;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
