//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class RegistrarDespachoObra
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlTracto;
        protected global::System.Web.UI.WebControls.DropDownList ddlConductor;
        protected global::System.Web.UI.WebControls.DropDownList ddlObra;
        protected global::System.Web.UI.WebControls.TextBox txtFechaSalida;
        protected global::System.Web.UI.WebControls.TextBox txtFechaLlegada;
        protected global::System.Web.UI.WebControls.TextBox txtFechaRetorno;
        protected global::System.Web.UI.WebControls.TextBox txtGalonesSalida;
        protected global::System.Web.UI.WebControls.TextBox txtGalonesRetorno;
        protected global::System.Web.UI.WebControls.TextBox txtObservaciones;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
