//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class RegistroPlantas
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Label lblTotalPlantas;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;
        protected global::System.Web.UI.WebControls.DropDownList ddlAmbito;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
        protected global::System.Web.UI.WebControls.GridView gvPlantas;
        protected global::System.Web.UI.WebControls.HiddenField hfIdPlanta;
        protected global::System.Web.UI.WebControls.TextBox txtEditarNombre;
        protected global::System.Web.UI.WebControls.DropDownList ddlEditarAmbito;
        protected global::System.Web.UI.WebControls.Button btnActualizarPlanta;
    }
}
