//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class RegistroPeajes
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
        protected global::System.Web.UI.WebControls.GridView gvPeajes;
        protected global::System.Web.UI.WebControls.Label lblTotalPeajes;
        protected global::System.Web.UI.WebControls.HiddenField hfIdEstacion;
        protected global::System.Web.UI.WebControls.TextBox txtEditarNombre;
        protected global::System.Web.UI.WebControls.Button btnActualizarPeaje;
    }
}
