//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class RegistroOperadores
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Label lblTotalOperadores;
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;
        protected global::System.Web.UI.WebControls.TextBox txtDNI;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDNI;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;
        protected global::System.Web.UI.WebControls.TextBox txtTelefono;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
        protected global::System.Web.UI.WebControls.GridView gvOperadores;
    }
}
