//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{
    public partial class RegistroEquiposMaquinaria
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.Label lblTotalEquipos;
        protected global::System.Web.UI.WebControls.Panel pnlFormulario;
        protected global::System.Web.UI.WebControls.TextBox txtPlaca;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPlaca;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipo;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvTipo;
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;
        protected global::System.Web.UI.WebControls.TextBox txtMarca;
        protected global::System.Web.UI.WebControls.TextBox txtModelo;
        protected global::System.Web.UI.WebControls.TextBox txtAnio;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;
        protected global::System.Web.UI.WebControls.GridView gvEquipos;
    }
}
