//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSGV.Views
{

    public partial class ReporteAbastecimiento
    {

        /// <summary>
        /// Control lblTotalRegistros.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalRegistros;

        /// <summary>
        /// Control txtFechaDesde.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaDesde;

        /// <summary>
        /// Control txtFechaHasta.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaHasta;

        /// <summary>
        /// Control txtBuscarConductor.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscarConductor;

        /// <summary>
        /// Control ddlRuta.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlRuta;

        /// <summary>
        /// Control btnBuscar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBuscar;

        /// <summary>
        /// Control btnLimpiar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        /// <summary>
        /// Control btnExportarExcel.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnExportarExcel;

        /// <summary>
        /// Control pnlResumen.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlResumen;

        /// <summary>
        /// Control lblTotalGLAbastecidos.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalGLAbastecidos;

        /// <summary>
        /// Control lblTotalGLConsumidos.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalGLConsumidos;

        /// <summary>
        /// Control lblTotalKM.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalKM;

        /// <summary>
        /// Control pnlReporte.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlReporte;

        /// <summary>
        /// Control gvReporte.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvReporte;

        /// <summary>
        /// Control pnlSinResultados.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlSinResultados;
    }
}
